name: NodeJS with Webpack

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: download compiler
      shell: cmd
      run: |
        curl "https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z" -L --output compiler &&^
        7z.exe x compiler

    - name: download cmake-3.26.1-windows-x86_64.zip
      shell: cmd
      run: curl https://github.com/Kitware/CMake/releases/download/v3.26.1/cmake-3.26.1-windows-x86_64.zip -L --output cmake-3.26.1-windows-x86_64.zip && dir && 7z.exe x cmake-3.26.1-windows-x86_64.zip

    - name: download PortableGit-2.38.1-64-bit.7z.exe
      shell: cmd
      run: curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe && dir && 7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"PortableGit-2.38.1-64-bit"
    
    - name: download python-3.10.8-amd64-portable
      shell: cmd
      run:  curl https://github.com/dirkarnez/python-portable/releases/download/v3.10.8/python-3.10.8-amd64-portable.zip -L --output python.zip && 7z.exe x python.zip -o"python-3.10.8-amd64-portable"
      
    - name: Build
      run: npm ci && npm run-script build

    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}
        
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: "dist"
        filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-node-v${{ matrix.node-version }}.zip"
        
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/${{ github.event.repository.name }}-${{ github.ref_name }}-node-v${{ matrix.node-version }}.zip"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
