name: sync-to-bitbucket
  
on: 
  push
  
jobs:
  build:
    if: github.actor == 'dirkarnez'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <-- clone with complete history
          
      - continue-on-error: true
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.SARURURURU_GIT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/user/repos \
          -d '{"name":"${{ github.event.repository.name }}","private": false}'
          
      - uses: yesolutions/mirror-action@v0.7.0
        with:
            REMOTE: 'git@github.com:sarurururu/${{ github.event.repository.name }}.git'
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
